"""add interview_mode and target_round to sessions

Revision ID: 01c4bed47451
Revises: 15585e6a3708
Create Date: 2026-06-29 15:07:30.347005
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c4bed47451'
down_revision: Union[str, None] = '15585e6a3708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column('interview_sessions', sa.Column('interview_mode', sa.String(length=20), nullable=False, server_default='full'))
    op.add_column('interview_sessions', sa.Column('target_round', sa.String(length=30), nullable=True))


def downgrade() -> None:
    op.drop_column('interview_sessions', 'target_round')
    op.drop_column('interview_sessions', 'interview_mode')
"""add interview_mode and target_round to sessions

Revision ID: 01c4bed47451
Revises: 15585e6a3708
Create Date: 2026-06-29 15:07:30.347005
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c4bed47451'
down_revision: Union[str, None] = '15585e6a3708'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('career_assessments_ibfk_1'), 'career_assessments', type_='foreignkey')
    op.create_foreign_key(None, 'career_assessments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('comments_ibfk_2'), 'comments', type_='foreignkey')
    op.drop_constraint(op.f('comments_ibfk_1'), 'comments', type_='foreignkey')
    op.create_foreign_key(None, 'comments', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'comments', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.add_column('interview_sessions', sa.Column('interview_mode', sa.String(length=20), nullable=False))
    op.add_column('interview_sessions', sa.Column('target_round', sa.String(length=30), nullable=True))
    op.drop_constraint(op.f('likes_ibfk_1'), 'likes', type_='foreignkey')
    op.drop_constraint(op.f('likes_ibfk_2'), 'likes', type_='foreignkey')
    op.create_foreign_key(None, 'likes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'likes', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('post_tags_ibfk_1'), 'post_tags', type_='foreignkey')
    op.drop_constraint(op.f('post_tags_ibfk_2'), 'post_tags', type_='foreignkey')
    op.create_foreign_key(None, 'post_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'post_tags', 'posts', ['post_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('posts_ibfk_1'), 'posts', type_='foreignkey')
    op.create_foreign_key(None, 'posts', 'users', ['author_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('resumes_ibfk_1'), 'resumes', type_='foreignkey')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('submissions_ibfk_1'), 'submissions', type_='foreignkey')
    op.drop_constraint(op.f('submissions_ibfk_2'), 'submissions', type_='foreignkey')
    op.create_foreign_key(None, 'submissions', 'problems', ['problem_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'submissions', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.drop_constraint(None, 'submissions', type_='foreignkey')
    op.create_foreign_key(op.f('submissions_ibfk_2'), 'submissions', 'problems', ['problem_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.create_foreign_key(op.f('submissions_ibfk_1'), 'submissions', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.create_foreign_key(op.f('resumes_ibfk_1'), 'resumes', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.create_foreign_key(op.f('posts_ibfk_1'), 'posts', 'users', ['author_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.drop_constraint(None, 'post_tags', type_='foreignkey')
    op.create_foreign_key(op.f('post_tags_ibfk_2'), 'post_tags', 'tags', ['tag_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.create_foreign_key(op.f('post_tags_ibfk_1'), 'post_tags', 'posts', ['post_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.drop_constraint(None, 'likes', type_='foreignkey')
    op.create_foreign_key(op.f('likes_ibfk_2'), 'likes', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.create_foreign_key(op.f('likes_ibfk_1'), 'likes', 'posts', ['post_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_column('interview_sessions', 'target_round')
    op.drop_column('interview_sessions', 'interview_mode')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.create_foreign_key(op.f('comments_ibfk_1'), 'comments', 'posts', ['post_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.create_foreign_key(op.f('comments_ibfk_2'), 'comments', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    op.drop_constraint(None, 'career_assessments', type_='foreignkey')
    op.create_foreign_key(op.f('career_assessments_ibfk_1'), 'career_assessments', 'users', ['user_id'], ['id'], onupdate='RESTRICT', ondelete='CASCADE')
    # ### end Alembic commands ###
